// SPDX-License-Identifier: Elastic-2.0
// Copyright (c) 2026 ClaymoreLab
import { useTranslation } from 'react-i18next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { CostFilters, ProjectCostSnapshot } from '@/types/project-costs';
import { bucketAmount, costMedia, mediaLabels, money } from './cost-format';
export function CostBreakdown({ snapshot, onFilter }: { snapshot: ProjectCostSnapshot; onFilter: (filters: CostFilters) => void }) {
  const { t } = useTranslation();
  return <div className="grid items-start gap-4 xl:grid-cols-[2fr_1fr]">
    <Card className="min-w-0"><CardHeader><CardTitle>{t('costs.breakdown', '渠道与媒体费用')}</CardTitle><p className="text-xs text-muted-foreground">{t('costs.breakdownHint', '点击费用查看对应调用，不改变项目总额')}</p></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[500px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="py-3 font-normal">{t('costs.channel', '渠道')}</th>{costMedia.map(media => <th className="text-right font-normal" key={media}>{t(`costs.media.${media}`, mediaLabels[media])}</th>)}</tr></thead><tbody>{snapshot.breakdown.channels.map(channel => <tr className="border-b last:border-0" key={channel.provider}><th className="py-4 text-left font-medium">{channel.provider}</th>{costMedia.map(media => { const bucket = channel.media.find(b => b.media_type === media); return <td className="text-right" key={media}>{bucket ? <button className="rounded-md px-2 py-2 tabular-nums hover:bg-muted focus-visible:outline-2 focus-visible:outline-primary" aria-label={`${channel.provider} ${t(`costs.media.${media}`, mediaLabels[media])}`} onClick={() => onFilter({ channel: channel.provider, media })}>{bucketAmount(bucket, t('costs.unpriced', '待核算'), t('costs.subscriptionCovered', '订阅覆盖'))}{bucket.unpriced_count > 0 && <span className="block text-xs text-amber-600">{t('costs.unknownCount', '{{count}} 次待核算', { count: bucket.unpriced_count })}</span>}</button> : <span className="px-2 text-muted-foreground">—</span>}</td>; })}</tr>)}</tbody></table>{!snapshot.breakdown.channels.length && <p className="py-6 text-center text-muted-foreground">{t('costs.noCalls', '暂无调用记录')}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{t('costs.mediaShare', '媒体费用占比')}</CardTitle><p className="text-xs text-muted-foreground">{t('costs.shareHint', '仅按已知费用计算')}</p></CardHeader><CardContent className="space-y-5">{costMedia.map(media => { const b = snapshot.breakdown.media.find(item => item.media_type === media); const share = b && snapshot.summary.total_cents > 0 ? b.total_cents / snapshot.summary.total_cents * 100 : null; return <div key={media}><div className="mb-2 flex justify-between text-sm"><span>{t(`costs.media.${media}`, mediaLabels[media])}</span><span className="tabular-nums">{b?.priced_count ? money(b.total_cents) : '—'}{share !== null && ` · ${share.toFixed(1)}%`}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary/70" style={{ width: `${share ?? 0}%` }} /></div></div>; })}</CardContent></Card>
  </div>;
}
