// SPDX-License-Identifier: Elastic-2.0
// Copyright (c) 2026 ClaymoreLab
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { useProjectCostEntries, useProjectCostEntry } from '@/lib/queries/project-costs';
import type { CostFilters, CostRevision, CostStatus, CostMedia } from '@/types/project-costs';
import { costDate, costFactLabel, costMedia, mediaLabels, money, statusLabels } from './cost-format';

function Facts({ facts }: { facts: Record<string, string | number | null | undefined> }) {
  return <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-sm">{Object.entries(facts).map(([key, value]) => <div className="contents" key={key}><dt className="text-muted-foreground">{key}</dt><dd className="min-w-0 break-all">{value ?? '—'}</dd></div>)}</dl>;
}
function Revision({ revision, amountCents }: { revision: CostRevision; amountCents?: number | null }) {
  const { t } = useTranslation();
  const rule = revision.rule_snapshot;
  // Current cost must use the API's lifecycle-aware amount. Only historical
  // audit revisions convert their recorded raw monetary fact for display.
  const displayedCents = amountCents === undefined
    ? (revision.value.amount_micros === null ? null : Math.floor((revision.value.amount_micros + 5000) / 10000))
    : amountCents;
  return <div className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{t(`costs.${revision.value.status}`, statusLabels[revision.value.status])}</strong><span>{displayedCents === null ? '—' : money(displayedCents)}</span></div><p className="text-xs text-muted-foreground">{costDate(revision.recorded_at)}{revision.applied !== undefined && ` · ${revision.applied ? t('costs.applied', '已采用') : t('costs.notApplied', '未覆盖当前费用')}`}</p>{revision.value.reason && <p className="text-sm">{revision.value.reason}</p>}{rule && <div className="space-y-2"><p className="text-sm font-medium">{t('costs.matchedRule', '匹配价格规则')}：{rule.id} / {rule.version}</p><p className="text-xs">{rule.currency} · {t('costs.rate', '人民币汇率')} {rule.cny_rate ?? '—'}</p>{rule.items.map(item => <p key={item.unit} className="text-xs">{costFactLabel(t, 'unit', item.unit)}：{item.unit_price} / {item.basis} · {t('costs.roundingStep', '取整步长')} {item.step} · {t('costs.minimum', '最低用量')} {item.minimum}</p>)}</div>}{revision.evidence && Object.keys(revision.evidence).length > 0 && <Facts facts={Object.fromEntries(Object.entries(revision.evidence).map(([key, value]) => [t(`costs.evidence.${key}`, key), value]))} />}{revision.usage && Object.keys(revision.usage).length > 0 && <Facts facts={Object.fromEntries(Object.entries(revision.usage).map(([key, value]) => [costFactLabel(t, 'unit', key), value]))} />}</div>;
}
function EntryDetail({ project, id, close }: { project: string; id: string | null; close: () => void }) {
  const { t } = useTranslation();
  const query = useProjectCostEntry(project, id);
  const detail = query.data;
  return <Sheet open={Boolean(id)} onOpenChange={open => { if (!open) close(); }}><SheetContent className="overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{t('costs.detail', '调用费用详情')}</SheetTitle><SheetDescription>{t('costs.detailHint', '费用依据与修订历史，均以北京时间展示')}</SheetDescription></SheetHeader><div className="space-y-5 px-4 pb-6">{query.isLoading && <p>{t('costs.loading', '正在加载费用…')}</p>}{query.isError && <div role="alert">{t('costs.loadError', '费用加载失败')}<Button variant="outline" onClick={() => query.refetch()}>{t('costs.retry', '重试')}</Button></div>}{detail && <><Facts facts={{ [t('costs.channel', '渠道')]: detail.attempt.provider, [t('costs.account', '账号')]: detail.attempt.account_id, [t('costs.model', '模型')]: detail.attempt.model, [t('costs.time', '时间')]: costDate(detail.attempt.occurred_at), [t('costs.submissionStatus', '提交状态')]: costFactLabel(t, 'submission', detail.attempt.submission_status), [t('costs.executionStatus', '执行状态')]: costFactLabel(t, 'execution', detail.attempt.execution_status), [t('costs.usageSource', '用量来源')]: costFactLabel(t, 'source', detail.attempt.usage_source), [t('costs.attemptId', '调用 ID')]: detail.attempt.attempt_id, [t('costs.externalId', '外部任务 ID')]: detail.attempt.external_id, [t('costs.taskId', '任务 ID')]: detail.attempt.task_id, [t('costs.resourceId', '资源 ID')]: detail.attempt.resource_id, [t('costs.workflow', '工作流')]: detail.attempt.workflow }} /><section className="space-y-3"><h3 className="font-medium">{t('costs.currentCost', '当前费用依据')}</h3><Revision revision={detail.current_cost} amountCents={detail.current_cost.amount_cents} />{detail.attempt.submission_status !== 'submitted' && <p className="text-sm text-amber-700 dark:text-amber-300">{t('costs.excludedSubmission', '该调用未确认提交，当前不计入按量费用。')}</p>}</section><section className="space-y-3"><h3 className="font-medium">{t('costs.revisions', '费用修订历史')}</h3>{detail.attempt.submission_status !== 'submitted' && <p className="text-xs text-muted-foreground">{t('costs.excludedAudit', '以下历史金额仅供审计，不代表当前计费金额。')}</p>}{detail.revisions.length ? detail.revisions.map((revision, index) => <Revision key={revision.event_id ?? index} revision={revision} />) : <p className="text-sm text-muted-foreground">{t('costs.noRevisions', '暂无修订记录')}</p>}</section></>}</div></SheetContent></Sheet>;
}
export function CostEntries({ project, filters, onFilter, channels }: { project: string; filters: CostFilters; onFilter: (filters: CostFilters) => void; channels: string[] }) {
  const { t } = useTranslation();
  const [cursors, setCursors] = useState<(string | null)[]>([null]);
  const [selected, setSelected] = useState<string | null>(null);
  const query = useProjectCostEntries(project, filters, cursors[cursors.length - 1]);
  const change = (value: CostFilters) => { setCursors([null]); onFilter(value); };
  const selectClass = 'h-9 rounded-md border bg-background px-3 text-sm';
  return <Card><CardHeader><CardTitle>{t('costs.ledger', '调用明细')}</CardTitle><div className="mt-2 flex flex-wrap gap-2"><label className="sr-only" htmlFor="cost-channel">{t('costs.channel', '渠道')}</label><select id="cost-channel" className={selectClass} value={filters.channel ?? ''} onChange={event => change({ ...filters, channel: event.target.value || undefined })}><option value="">{t('costs.allChannels', '全部渠道')}</option>{channels.map(channel => <option key={channel}>{channel}</option>)}</select><label className="sr-only" htmlFor="cost-media">{t('costs.mediaType', '媒体类型')}</label><select id="cost-media" className={selectClass} value={filters.media ?? ''} onChange={event => change({ ...filters, media: event.target.value as CostMedia || undefined })}><option value="">{t('costs.allMedia', '全部媒体')}</option>{costMedia.map(media => <option key={media} value={media}>{t(`costs.media.${media}`, mediaLabels[media])}</option>)}</select><label className="sr-only" htmlFor="cost-status">{t('costs.costStatus', '费用状态')}</label><select id="cost-status" className={selectClass} value={filters.status ?? ''} onChange={event => change({ ...filters, status: event.target.value as CostStatus || undefined })}><option value="">{t('costs.allStatuses', '全部费用状态')}</option>{Object.entries(statusLabels).map(([key, value]) => <option key={key} value={key}>{t(`costs.${key}`, value)}</option>)}</select><Button variant="ghost" onClick={() => change({})}>{t('costs.clearFilters', '清除筛选')}</Button></div></CardHeader><CardContent>
    {query.isError && <div role="alert" className="mb-3 text-sm text-destructive">{t('costs.loadError', '费用加载失败')} <Button variant="outline" onClick={() => query.refetch()}>{t('costs.retry', '重试')}</Button></div>}
    {query.isLoading ? <p className="py-6 text-center text-muted-foreground">{t('costs.loading', '正在加载费用…')}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b text-muted-foreground">{['time', 'channel', 'account', 'model', 'mediaType', 'usage', 'usageSource', 'costStatus', 'amount', 'detail'].map((key, index) => <th className="py-3 pr-4 font-normal" key={key}>{t(`costs.${key}`, ['时间', '渠道', '账号', '模型', '媒体类型', '用量', '用量来源', '费用状态', '费用', '详情'][index])}</th>)}</tr></thead><tbody>{query.data?.entries.map(entry => <tr className="border-b last:border-0" key={entry.attempt_id}><td className="whitespace-nowrap py-4 pr-4 text-xs">{costDate(entry.occurred_at)}</td><td className="pr-4">{entry.provider}</td><td className="max-w-40 break-words pr-4">{entry.account_id}</td><td className="max-w-40 break-words pr-4">{entry.model}</td><td className="pr-4">{t(`costs.media.${entry.media_type}`, mediaLabels[entry.media_type])}</td><td className="pr-4 text-xs">{Object.entries(entry.usage).map(([key, value]) => <div key={key}>{costFactLabel(t, 'unit', key)}: {value}</div>)}</td><td className="pr-4 text-xs">{costFactLabel(t, 'source', entry.usage_source)}</td><td className="pr-4">{entry.submission_status === 'pending' ? t('costs.pending', '待提交确认') : entry.submission_status === 'failed' ? t('costs.notSubmitted', '未提交') : t(`costs.${entry.cost_status}`, statusLabels[entry.cost_status])}</td><td className="pr-4 tabular-nums">{entry.amount_cents === null ? '—' : money(entry.amount_cents)}</td><td><Button variant="ghost" size="sm" onClick={() => setSelected(entry.attempt_id)}>{t('costs.view', '查看')}</Button></td></tr>)}</tbody></table>{query.data?.entries.length === 0 && <p className="py-8 text-center text-muted-foreground">{t('costs.noCalls', '暂无调用记录')}</p>}</div>}
    <div className="mt-4 flex items-center justify-end gap-3"><span className="text-xs text-muted-foreground">{t('costs.page', '第 {{count}} 页', { count: cursors.length })}</span><Button variant="outline" disabled={cursors.length === 1 || query.isFetching} onClick={() => setCursors(previous => previous.slice(0, -1))}>{t('costs.previous', '上一页')}</Button><Button variant="outline" disabled={!query.data?.next_cursor || query.isFetching} onClick={() => setCursors(previous => [...previous, query.data!.next_cursor])}>{t('costs.next', '下一页')}</Button></div>
    <EntryDetail project={project} id={selected} close={() => setSelected(null)} />
  </CardContent></Card>;
}
