packages:
  - "."
  - "frontend"

onlyBuiltDependencies:
  - electron
  - electron-winstaller

blockExoticSubdeps: false
verifyDepsBeforeRun: false

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: false
  msw: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
