import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { DirectorStudio } from "./director-studio";
const mocks = vi.hoisted(() => ({ revisions: [] as Array<{ revision_id: string; status: string; groups: Array<{ id: string; shots: Array<{ id: string; subject: string; camera_motion: string; composition: string }> }> }>, edit: vi.fn(), post: vi.fn(), put: vi.fn(async (_path: string, options: { json: { name: string; data: unknown } }) => new Response(JSON.stringify({ ok: true, data: { id: "saved", name: options.json.name, data: options.json.data, revision: 1 } }), { status: 200 })) }));
vi.mock("@/lib/api", () => ({ api: { get: () => ({ json: async () => ({ data: [] }) }), post: mocks.post, put: mocks.put } }));
vi.mock("@/lib/queries/episodes", () => ({ useEpisodes: () => ({ data: { data: [{ number: 1, title: "实际剧集" }] } }) }));
vi.mock("@/lib/queries/tasks", () => ({ useTasks: () => ({ data: { data: [] }, refetch: vi.fn() }) }));
vi.mock("@/lib/queries/director-plans", () => ({ directorPlanKeys: { all: () => [] }, useDirectorPlans: () => ({ data: { ok: true, data: mocks.revisions } }), useEditDirectorPlan: () => ({ mutateAsync: mocks.edit }) }));
vi.mock("@/components/episode/director-review/director-review-workbench", () => ({ DirectorReviewWorkbench: () => <div>真实方案审阅入口</div> }));
vi.mock("./director-adaptations", () => ({ DirectorAdaptations: () => <div>独立改编审阅</div> }));
describe("DirectorStudio", () => {
  it('explicitly imports a legacy method into an existing team without replacing the form on selection', async () => {
    const client = new QueryClient({ defaultOptions: { queries: { staleTime: Infinity } } });
    const overrides = { writer: { brief: { prompt: '保留编剧方法' } } };
    client.setQueryData(['agent-team', 'migration'], { draft: { draft_revision: 4, data: { template_id: 'builtin', template_revision: 1, overrides } }, active: null, effective: { director: { director_plan: { config: { director_preferences: { camera_motion: '共享运镜' } } } } } });
    client.setQueryData(['studios', 'migration', 'director'], { data: [{ id: 'legacy', name: '旧方法', revision: 7, data: { camera_motion: '旧运镜' } }] });
    mocks.post.mockImplementationOnce(() => new Promise<Response>(() => {}));
    render(<QueryClientProvider client={client}><DirectorStudio project="migration" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByLabelText('运镜')).toHaveValue('共享运镜'));
    fireEvent.change(screen.getByLabelText('导入已保存导演方法'), { target: { value: 'legacy' } });
    expect(screen.getByLabelText('运镜')).toHaveValue('共享运镜');
    expect(mocks.post).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: '将所选旧配置导入团队草稿（不启用）' }));
    await waitFor(() => expect(mocks.post).toHaveBeenCalledOnce());
    expect(mocks.post.mock.calls[0][0]).toContain('/agent-team/import-director-method');
    expect(mocks.post.mock.calls[0][1].json).toEqual({ document_id: 'legacy', expected_document_revision: 7, expected_draft_revision: 4 });
    expect(client.getQueryData<{ draft: { data: { overrides: unknown } } }>(['agent-team', 'migration'])?.draft.data.overrides).toEqual(overrides);
  });
  it('reads the shared draft and submits the active version without a legacy document', async () => {
    const client = new QueryClient({ defaultOptions: { queries: { staleTime: Infinity } } });
    client.setQueryData(['agent-team', 'shared'], { draft: { draft_revision: 3, data: { template_id: 'builtin', template_revision: 1, overrides: {} } }, active: { active_revision: 2 }, effective: { director: { director_plan: { config: { director_preferences: { camera_motion: '共享运镜' } } } } } });
    mocks.post.mockResolvedValue(new Response(JSON.stringify({ task_id: 'team-task', status: 'queued', reused: false })));
    render(<QueryClientProvider client={client}><DirectorStudio project="shared" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    await waitFor(() => expect(screen.getByLabelText('运镜')).toHaveValue('共享运镜'));
    expect(screen.getByText(/团队共享草稿 v3/)).toBeInTheDocument();
    expect(screen.getByRole('checkbox', { name: /允许提出故事/ })).toBeDisabled();
    fireEvent.change(screen.getByLabelText('运镜'), { target: { value: '未保存运镜' } });
    fireEvent.click(screen.getByRole('button', { name: /^AI 整集规划/ }));
    fireEvent.change(screen.getByLabelText('应用到集'), { target: { value: '1' } });
    fireEvent.click(screen.getByRole('button', { name: '按团队启用 v2 生成 AI 整集方案' }));
    await waitFor(() => expect(mocks.post).toHaveBeenCalledOnce());
    expect(mocks.post.mock.calls[0][0]).toContain('/agent-team/director-plan');
    expect(mocks.post.mock.calls[0][1].json).toEqual({ episode: 1, expected_active_revision: 2 });
    expect(screen.getByLabelText('运镜')).toHaveValue('未保存运镜');
  });
  beforeEach(() => { mocks.revisions = []; mocks.edit.mockReset(); mocks.post.mockReset(); mocks.put.mockClear(); });
  it("selects a visual preset, edits its actual parameters, and saves without a model call", async () => {
    mocks.put.mockClear(); mocks.post.mockClear();
    render(<QueryClientProvider client={new QueryClient()}><DirectorStudio project="preset-cards" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    fireEvent.click(screen.getByRole('button', { name: 'TVC 广告' }));
    expect(screen.getByRole('button', { name: 'TVC 广告' })).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByLabelText('配置名称')).toHaveValue('TVC 广告');
    fireEvent.click(screen.getByText('高级导演参数'));
    expect(screen.getByLabelText('运镜')).toHaveValue('平稳推进与产品细节特写，转场保持运动方向连续');
    fireEvent.change(screen.getByLabelText('运镜'), { target: { value: '围绕主体做缓慢环绕' } });
    fireEvent.click(screen.getByRole('button', { name: /保存配置版本/ }));
    await waitFor(() => expect(mocks.put).toHaveBeenCalledOnce());
    expect(mocks.put.mock.calls[0][1].json.data).toMatchObject({ camera_motion: '围绕主体做缓慢环绕', allow_adaptation: false });
    expect(mocks.post).not.toHaveBeenCalled();
    expect(screen.getByRole('button', { name: /优化已有镜头/ })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /^AI 整集规划/ })).toBeInTheDocument();
    mocks.put.mockClear();
  });
  it("prevents loading another configuration while a save is pending", async () => {
    let resolve!: (response: Response) => void;
    mocks.put.mockImplementationOnce(() => new Promise<Response>((done) => { resolve = done; }));
    render(<QueryClientProvider client={new QueryClient()}><DirectorStudio project="pending" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    fireEvent.click(screen.getByRole("button", { name: /保存配置版本/ }));
    await waitFor(() => expect(screen.getByLabelText("重新加载已保存配置")).toBeDisabled());
    fireEvent.change(screen.getByLabelText("配置名称"), { target: { value: "保存期间的新修改" } });
    resolve(new Response(JSON.stringify({ ok: true, data: { id: "saved", name: "我的导演方法", data: {}, revision: 1 } })));
    await waitFor(() => expect(screen.getByLabelText("重新加载已保存配置")).toBeEnabled());
    expect(screen.getByLabelText("配置名称")).toHaveValue("保存期间的新修改");
    expect(screen.getByText("提交的版本已保存；保存期间新增的修改仍未保存，请再次保存。")).toBeInTheDocument();
    mocks.put.mockClear();
  });
  it("keeps adaptation opt-in and does not call a model while editing or saving", async () => {
    render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><DirectorStudio project="real-project" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    expect(screen.getByRole("checkbox", { name: /允许提出故事/ })).not.toBeChecked();
    fireEvent.click(screen.getByRole("button", { name: "克制观察" }));
    fireEvent.click(screen.getByRole("button", { name: /保存配置版本/ }));
    await waitFor(() => expect(mocks.put).toHaveBeenCalledOnce());
    expect(mocks.put.mock.calls[0][1].json.data).toMatchObject({ allow_adaptation: false, performance: "克制、自然，强调细微反应" });
    expect(mocks.post).not.toHaveBeenCalled();
  });
  it('preserves local preview and per-shot adoption through the simplified flow', async () => {
    mocks.revisions = [{ revision_id: 'r1', status: 'draft', groups: [{ id: 'g1', shots: [{ id: 's1', subject: '角色观察窗外', camera_motion: '原运镜', composition: '原构图' }] }] }];
    mocks.edit.mockResolvedValue({ ok: true, data: { revision_id: 'r2' } });
    render(<QueryClientProvider client={new QueryClient()}><DirectorStudio project="existing-shots" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    fireEvent.click(screen.getByRole('button', { name: '纪录片' }));
    fireEvent.click(screen.getByRole('button', { name: /保存配置版本/ }));
    await waitFor(() => expect(screen.getByText('配置版本已保存，可生成镜头建议。')).toBeInTheDocument());
    fireEvent.change(screen.getByLabelText('应用到集'), { target: { value: '1' } });
    fireEvent.change(screen.getByLabelText('基于方案版本'), { target: { value: 'r1' } });
    fireEvent.click(screen.getByRole('button', { name: '生成可比较建议' }));
    expect(screen.getByText('原运镜')).toBeInTheDocument();
    expect(screen.getAllByText('以观察式固定机位和轻微跟拍呈现现场关系').length).toBeGreaterThan(0);
    fireEvent.click(screen.getByRole('button', { name: '采纳此镜头' }));
    await waitFor(() => expect(mocks.edit).toHaveBeenCalledOnce());
    expect(mocks.edit.mock.calls[0][0]).toEqual({ revisionId: 'r1', command: { kind: 'update_shot', shot_id: 's1', changes: { camera_motion: '以观察式固定机位和轻微跟拍呈现现场关系', composition: '人物与环境共同叙事，避免过度摆拍式对称' } } });
    expect(mocks.post).not.toHaveBeenCalled();
  });
  it('separates AI planning selection from the explicit paid submission', async () => {
    mocks.post.mockResolvedValue(new Response(JSON.stringify({ ok: true, task_id: 'task-1', status: 'queued', reused: false })));
    render(<QueryClientProvider client={new QueryClient()}><DirectorStudio project="ai-plan" /></QueryClientProvider>);
    await waitFor(() => expect(screen.getByRole("button", { name: /保存配置版本/ })).toBeEnabled());
    fireEvent.click(screen.getByRole('button', { name: '动画剧情' }));
    fireEvent.click(screen.getByRole('button', { name: /保存配置版本/ }));
    await waitFor(() => expect(screen.getByText('配置版本已保存，可生成镜头建议。')).toBeInTheDocument());
    fireEvent.click(screen.getByRole('button', { name: /^AI 整集规划/ }));
    fireEvent.change(screen.getByLabelText('应用到集'), { target: { value: '1' } });
    expect(mocks.post).not.toHaveBeenCalled();
    expect(screen.queryByLabelText('基于方案版本')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: '按已保存方法生成 AI 整集方案' }));
    await waitFor(() => expect(mocks.post).toHaveBeenCalledOnce());
    expect(mocks.post.mock.calls[0][1].json).toEqual({ episode: 1, expected_revision: 1, allow_adaptation: false });
  });
});
