import { useState } from 'react';
import { Button } from '@/components/ui/button';
import type { MethodConfig, ResourceVersion, TaskRoute } from './types';
const control = 'w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-sm text-zinc-100';
const fieldNames: Record<keyof MethodConfig, string> = { prompt: '工作提示词', model: '模型路由', skills: '技能', references: '参考资料', director_preferences: '导演偏好' };
export function MethodEditor({ role, method, overrides, resources, disabled, onChange, onRestore }: { role: string; method: MethodConfig; overrides: Partial<MethodConfig>; resources: ResourceVersion[]; disabled: boolean; onChange: <K extends keyof MethodConfig>(field: K, value: MethodConfig[K]) => void; onRestore: (field: keyof MethodConfig) => void }) {
  const [expanded, setExpanded] = useState(false);
  const heading = (field: keyof MethodConfig) => <div className="mb-2 flex items-center gap-3"><span className="text-sm font-medium">{fieldNames[field]}</span><span className="text-xs text-zinc-400">{Object.prototype.hasOwnProperty.call(overrides, field) ? '项目覆盖' : '继承模板'}</span>{Object.prototype.hasOwnProperty.call(overrides, field) && <Button size="sm" variant="ghost" disabled={disabled} onClick={() => onRestore(field)}>恢复继承</Button>}</div>;
  return <fieldset disabled={disabled} className="space-y-6 disabled:opacity-60">
    <section>{heading('prompt')}<p className="mb-2 text-xs text-zinc-400">留空沿用现有方法。补充提示词会在固定任务协议内追加创作指导。</p><textarea aria-label="工作提示词" className={`${control} ${expanded ? 'min-h-[65vh]' : 'min-h-52'} resize-y`} value={method.prompt} onChange={event => onChange('prompt', event.target.value)} placeholder="补充此子任务的创作方法、风格与关注点" /><Button size="sm" variant="ghost" onClick={() => setExpanded(!expanded)}>{expanded ? '收起编辑器' : '展开编辑器'}</Button></section>
    <section>{heading('model')}<select aria-label="模型选择方式" className={control} value={method.model === 'project' ? 'project' : 'explicit'} onChange={event => onChange('model', event.target.value === 'project' ? 'project' : { runtime: 'model_api', model: 'deepseek-v4-flash', fallback: 'stop' })}><option value="project">跟随项目模型设置</option><option value="explicit">此子任务指定模型</option></select>{method.model !== 'project' && <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs">运行方式<select aria-label="运行方式" className={control} value={method.model.runtime} onChange={e => onChange('model', { ...method.model as TaskRoute, runtime: e.target.value as TaskRoute['runtime'] })}>{['model_api','codex','workbuddy','deepseek_harness'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-xs">模型标识<input aria-label="模型标识" className={control} value={method.model.model} onChange={e => onChange('model', { ...method.model as TaskRoute, model: e.target.value })} /></label><label className="text-xs">推理强度<select aria-label="推理强度" className={control} value={method.model.reasoning_effort ?? ''} onChange={e => onChange('model', { ...method.model as TaskRoute, reasoning_effort: e.target.value || null })}><option value="">默认</option>{['none','minimal','low','medium','high','xhigh','max'].map(v => <option key={v}>{v}</option>)}</select></label></div>}</section>
    {(['skills','references'] as const).map(field => <section key={field}>{heading(field)}<p className="mb-2 text-xs text-zinc-400">引用固定版本，资源库更新不会自动改变此方法。</p><div className="space-y-2">{method[field].map(ref => <div key={`${ref.id}:${ref.revision}`} className="flex items-center justify-between rounded-lg border border-zinc-800 p-2 text-sm"><span>{ref.id} · v{ref.revision}</span><Button size="sm" variant="ghost" aria-label={`移除 ${ref.id}`} onClick={() => onChange(field, method[field].filter(item => item.id !== ref.id || item.revision !== ref.revision))}>移除</Button></div>)}</div><select aria-label={`添加${fieldNames[field]}版本`} className={`${control} mt-2`} value="" onChange={e => { const resource = resources.find(r => `${r.id}:${r.revision}` === e.target.value); if (resource) onChange(field, [...method[field], { id: resource.id, revision: resource.revision }]); }}><option value="">选择固定资源版本…</option>{resources.filter(r => r.kind === (field === 'skills' ? 'skill' : 'reference') && !r.archived && !method[field].some(ref => ref.id === r.id)).map(r => <option value={`${r.id}:${r.revision}`} key={`${r.id}:${r.revision}`}>{r.id} · v{r.revision}</option>)}</select><Button variant="ghost" size="sm" onClick={() => onChange(field, [])}>明确不使用{fieldNames[field]}</Button></section>)}
    {role === 'director' && <section>{heading('director_preferences')}<div className="grid gap-3 sm:grid-cols-2">{Object.entries({ pace: '节奏', camera_motion: '镜头运动', composition: '构图', performance: '表演', method: '导演方法' }).map(([key,label]) => <label key={key} className="text-sm">{label}<textarea aria-label={label} className={control} value={method.director_preferences[key] ?? ''} onChange={e => onChange('director_preferences', { ...method.director_preferences, [key]: e.target.value })} /></label>)}</div><Button variant="ghost" size="sm" onClick={() => onChange('director_preferences', {})}>明确不使用导演偏好</Button></section>}
    <details className="rounded-lg border border-zinc-800 p-4 text-xs text-zinc-400"><summary className="cursor-pointer text-zinc-200">输入、输出与执行协议（只读）</summary><p className="mt-3">输入由所选子任务提供项目素材与当前文档版本。输出沿用该任务要求的结构化结果，并通过原有校验后进入制作流程。</p><p className="mt-2">这里编辑创作方法，不能改变系统协议或输出字段。启用后，新任务会冻结方法、模型和资源版本；已运行任务保持原快照。</p></details>
  </fieldset>;
}
