import { act, fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { TemplatePanel } from './template-panel';
import { ResourceLibrary } from './resource-library';
import { TrialCandidate, TrialPanel } from './trial-panel';
import { MethodTrace } from './method-trace';
import { MethodEditor } from './method-editor';
import { defaultMethod, type TeamOverview, type ResourceVersion, type TeamTemplate } from './types';
import * as tools from './tools-api';
import * as api from './api';
vi.mock('./tools-api', async original => ({ ...await original<typeof import('./tools-api')>(), read: vi.fn(), post: vi.fn(), publish: vi.fn(), templates: vi.fn(), upgrade: vi.fn() }));
vi.mock('./api');
const resource: ResourceVersion = { id: 'craft', revision: 1, content: '技法原文', kind: 'skill', owner: 'me', archived: false, content_hash: 'hash' };
const template = { id: 'builtin', revision: 1, name: '默认', owner: 'builtin', roles: { writer: { brief: defaultMethod } } };
const overview: TeamOverview = { template, catalog: [], connectivity: {}, active: null, draft: { draft_revision: 2, data: { template, template_id: 'builtin', template_revision: 1, overrides: { writer: { brief: { prompt: '项目覆盖', skills: [{ id: 'craft', revision: 1 }] } } } } }, effective: { writer: { brief: { config: defaultMethod, origins: { model: 'template', prompt: 'project', skills: 'project', references: 'template', director_preferences: 'template' }, trial_supported: true } } } };
const props = { project: 'p', overview, disabled: false, selectedRole: 'writer', selectedSubtask: 'brief', onChanged: vi.fn() };
function mount(child: React.ReactNode) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}>{child}</QueryClientProvider>); }
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.getTeamResources).mockResolvedValue([resource]); vi.mocked(tools.templates).mockResolvedValue([template]); vi.mocked(tools.read).mockResolvedValue([]); });
afterEach(cleanup);
it('compares upgrade and submits fixed version with CAS without altering overrides', async () => {
  const next = { ...template, id: 'personal', revision: 3, roles: { writer: { brief: { ...defaultMethod, prompt: '新模板' } } } };
  vi.mocked(tools.templates).mockResolvedValue([next]);
  mount(<TemplatePanel {...props} />);
  await screen.findByRole('option', { name: '默认 · v3' });
  fireEvent.change(screen.getByLabelText('选择模板'), { target: { value: 'personal' } });
  expect(screen.getByText(/项目覆盖保留/)).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: '将此固定版本应用到草稿' }));
  await waitFor(() => expect(tools.upgrade).toHaveBeenCalledWith('p', next, 2));
  expect(overview.draft!.data.overrides.writer.brief.prompt).toBe('项目覆盖');
});
it('publishes immutable resource without changing pins, then explicitly applies new version', async () => {
  vi.mocked(tools.publish).mockResolvedValue({ ...resource, revision: 2, content: '新技法' });
  mount(<ResourceLibrary {...props} />);
  await screen.findByRole('option', { name: /craft/ });
  fireEvent.change(screen.getByLabelText('选择资源'), { target: { value: 'craft' } });
  fireEvent.change(screen.getByLabelText('资源正文'), { target: { value: '新技法' } });
  fireEvent.click(screen.getByRole('button', { name: '发布新修订 v2' }));
  await screen.findByText('已发布不可变版本。现有固定引用保持原版本。');
  expect(api.saveTeamDraft).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: '将此版本用于当前方法草稿' }));
  await waitFor(() => expect(api.saveTeamDraft).toHaveBeenCalled());
  expect(vi.mocked(api.saveTeamDraft).mock.calls[0][1].overrides.writer.brief.skills).toEqual([{ id: 'craft', revision: 2 }]);
});
it('uses frozen history and permits retry only on failed side, with absent cost explicit', async () => {
  const trial = { id: 'trial', created_at: '2026', role_id: 'writer', subtask_id: 'brief', frozen_input: { historical: true }, methods: { old: '方法快照' }, sides: { active: { status: 'completed', attempt: 1, duration_seconds: null, cost: null, candidate: '旧输出', error: null }, draft: { status: 'failed', attempt: 1, duration_seconds: 1, cost: null, candidate: null, error: '失败' } } };
  vi.mocked(tools.read).mockImplementation(async path => (path.includes('trial-inputs') ? { trial_supported: true, documents: [], sources: [] } : path.endsWith('/trials') ? [trial] : trial) as never);
  vi.mocked(tools.post).mockResolvedValue(trial);
  mount(<TrialPanel {...props} />);
  await screen.findByRole('option', { name: /2026/ });
  fireEvent.change(screen.getByLabelText('试运行历史'), { target: { value: 'trial' } });
  await screen.findByText('旧输出');
  expect(screen.getAllByText(/成本 未提供/)).toHaveLength(2);
  expect(screen.queryByRole('button', { name: '仅重试基线侧' })).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: '仅重试草稿侧' }));
  await waitFor(() => expect(tools.post).toHaveBeenCalledWith('api/v1/projects/p/agent-team/trials/trial/retry-side', { side: 'draft' }));
  expect(screen.getByText(/方法快照/)).toBeInTheDocument();
  expect(screen.getByRole('button', { name: '开始双侧试运行' })).toBeDisabled();
});
it('renders actual task snapshot rather than current configuration', () => {
  render(<MethodTrace metadata={{ agent_team_snapshots: [{ role_id: 'writer', subtask_id: 'brief', template_id: 'historical', template_revision: 4, active_revision: 7, resolved_model: { runtime: 'codex', model: 'old-model' }, resource_snapshots: [resource] }] }} />);
  expect(screen.getByText(/historical v4/)).toBeInTheDocument();
  expect(screen.getByText(/old-model/)).toBeInTheDocument();
});
it('retains the request id on uncertain submission and rejects stale episode selections', async () => {
  const inputs = { trial_supported: true, documents: [{ id: 'd', revision_id: 'r', title: '已保存' }], sources: [] };
  vi.mocked(tools.read).mockImplementation(async path => (path.includes('trial-inputs') ? inputs : []) as never);
  vi.mocked(tools.post).mockRejectedValue(new Error('网络中断'));
  mount(<TrialPanel {...props} />);
  fireEvent.click(await screen.findByRole('checkbox'));
  fireEvent.change(screen.getByLabelText('试运行目标集'), { target: { value: '2' } });
  expect(screen.getByRole('button', { name: '开始双侧试运行' })).toBeDisabled();
  fireEvent.change(screen.getByLabelText('试运行目标集'), { target: { value: '1' } });
  fireEvent.click(await screen.findByRole('checkbox'));
  await waitFor(() => expect(screen.getByRole('button', { name: '开始双侧试运行' })).toBeEnabled());
  fireEvent.click(screen.getByRole('button', { name: '开始双侧试运行' }));
  await screen.findByText(/网络中断/);
  const first = vi.mocked(tools.post).mock.calls[0][1];
  fireEvent.click(screen.getByRole('button', { name: '按原请求重试提交（不会重复创建）' }));
  await waitFor(() => expect(tools.post).toHaveBeenCalledTimes(2));
  expect(vi.mocked(tools.post).mock.calls[1][1]).toEqual(first);
});
it('locks template editors during publish and normalizes saved JSON without a false dirty state', async () => {
  const personal = { ...template, id: 'personal' };
  vi.mocked(tools.templates).mockResolvedValue([personal]);
  let finish!: (result: TeamTemplate) => void;
  vi.mocked(tools.publish).mockImplementation(() => new Promise(resolve => { finish = resolve as typeof finish; }));
  mount(<TemplatePanel {...props} />);
  await screen.findByRole('option', { name: '默认 · v1' });
  fireEvent.change(screen.getByLabelText('选择模板'), { target: { value: 'personal' } });
  fireEvent.click(screen.getByText('编辑并发布新修订'));
  fireEvent.change(screen.getByLabelText('模板方法 JSON'), { target: { value: JSON.stringify(personal.roles) } });
  fireEvent.click(screen.getByRole('button', { name: '发布新修订 v2' }));
  expect(screen.getByLabelText('模板名称')).toBeDisabled();
  expect(screen.getByLabelText('模板方法 JSON')).toBeDisabled();
  await act(async () => finish({ ...personal, revision: 2 }));
  await waitFor(() => expect(screen.getByLabelText('选择模板')).toBeEnabled());
  expect(screen.getByLabelText('模板方法 JSON')).toHaveValue(JSON.stringify(personal.roles, null, 2));
  expect(screen.queryByRole('button', { name: '放弃模板编辑' })).not.toBeInTheDocument();
});
it('renders candidate Markdown and keeps structured validation details collapsed', () => {
  render(<TrialCandidate candidate={{ markdown: '# 正文标题\n\n角色对白。', validation_report: { passed: true } }} />);
  expect(screen.getByRole('heading', { name: '正文标题' })).toBeInTheDocument();
  expect(screen.getByText('角色对白。')).toBeInTheDocument();
  expect(screen.getByText('校验结果：通过')).toBeInTheDocument();
  expect(screen.getByText('结构化候选与校验详情').closest('details')).not.toHaveAttribute('open');
});
it('displays the frozen title when personal library identity collides with a pinned snapshot', () => {
  render(<MethodEditor role="writer" method={{ ...defaultMethod, skills: [{ id: resource.id, revision: resource.revision }] }} overrides={{}} resources={[{ ...resource, content: '# 个人库同名版本', owner: 'other' }]} resourceSnapshots={[{ ...resource, content: '# 已冻结技法标题' }]} disabled={false} onChange={vi.fn()} onRestore={vi.fn()} />);
  expect(screen.getByText(/已冻结技法标题 · v1/)).toBeInTheDocument();
  expect(screen.queryByText(/个人库同名版本/)).not.toBeInTheDocument();
});
