import { act, fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { BackendStatusError } from '@/lib/api-errors';
import { TeamStudio } from './team-studio';
import * as api from './api';
import { defaultMethod, type TeamOverview, type TeamDraft } from './types';
import { readStudioContext, studioLocation } from '../studio-context';
vi.mock('./api');
const mock = vi.mocked(api);
let overview: TeamOverview;
function fixture(): TeamOverview { return { catalog: [{ id: 'writer', name: '编剧', subtasks: ['brief', 'outline'], connected: true }], template: { id: 'builtin', revision: 1, name: '默认团队', owner: 'builtin', roles: { writer: { brief: { ...defaultMethod, prompt: '模板提示' }, outline: defaultMethod } } }, draft: null, active: null, effective: {}, connectivity: { writer: { brief: true, outline: false } } }; }
function mount() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><TeamStudio project="p" /></QueryClientProvider>); }
beforeEach(() => { vi.resetAllMocks(); overview = fixture(); mock.getTeam.mockImplementation(async () => structuredClone(overview)); mock.getTeamResources.mockResolvedValue([]); mock.getTeamDiff.mockResolvedValue([]); mock.getTeamVersions.mockResolvedValue([]); mock.saveTeamDraft.mockImplementation(async (_project, data, revision) => { const draft = { draft_revision: revision + 1, data: { ...data, template: overview.template } }; overview = { ...overview, draft }; return draft; }); });
afterEach(cleanup);
describe('Agent Team editing', () => {
  it('saves only a draft and restores field inheritance', async () => { mount(); const prompt = await screen.findByLabelText('工作提示词'); expect(prompt).toHaveValue('模板提示'); fireEvent.change(prompt, { target: { value: '项目方法' } }); fireEvent.click(screen.getByRole('button', { name: '保存草稿' })); await waitFor(() => expect(mock.saveTeamDraft).toHaveBeenCalledOnce()); expect(mock.saveTeamDraft.mock.calls[0][1]).toEqual({ template_id: 'builtin', template_revision: 1, overrides: { writer: { brief: { prompt: '项目方法' } } } }); expect(mock.activateTeam).not.toHaveBeenCalled(); expect(screen.getByText(/尚未启用 · 沿用现有方法/)).toBeInTheDocument(); await waitFor(() => expect(screen.getByRole('button', { name: '保存草稿' })).toBeDisabled()); fireEvent.click(screen.getByRole('button', { name: '恢复继承' })); expect(prompt).toHaveValue('模板提示'); });
  it('keeps changes when switching subtasks and blocks disconnected customization', async () => { mount(); const prompt = await screen.findByLabelText('工作提示词'); fireEvent.change(prompt, { target: { value: '保留文字' } }); fireEvent.click(screen.getByRole('button', { name: /故事大纲/ })); fireEvent.change(screen.getByLabelText('工作提示词'), { target: { value: '未接入自定义' } }); fireEvent.click(screen.getByRole('button', { name: /创作简报/ })); expect(screen.getByLabelText('工作提示词')).toHaveValue('保留文字'); expect(screen.getByText('未接入子任务含自定义配置，暂不能启用团队。')).toBeInTheDocument(); expect(screen.getByRole('button', { name: '启用已保存草稿' })).toBeDisabled(); });
  it('does not clear edits entered while saving or during refetch', async () => { let finish!: (value: TeamDraft) => void; mock.saveTeamDraft.mockImplementation(() => new Promise(resolve => { finish = resolve; })); mount(); const prompt = await screen.findByLabelText('工作提示词'); fireEvent.change(prompt, { target: { value: '保存版本' } }); fireEvent.click(screen.getByRole('button', { name: '保存草稿' })); fireEvent.change(prompt, { target: { value: '更新文字' } }); await act(async () => finish({ draft_revision: 1, data: { template: overview.template, template_id: 'builtin', template_revision: 1, overrides: { writer: { brief: { prompt: '保存版本' } } } } })); await waitFor(() => expect(screen.getByRole('button', { name: '保存草稿' })).toBeEnabled()); expect(prompt).toHaveValue('更新文字'); });
  it('keeps text on conflict until explicit discard and reload', async () => { mock.saveTeamDraft.mockRejectedValue(new BackendStatusError('revision conflict', 409)); mount(); const prompt = await screen.findByLabelText('工作提示词'); fireEvent.change(prompt, { target: { value: '本地文字' } }); overview.draft = { draft_revision: 7, data: { template_id: 'builtin', template_revision: 1, template: overview.template, overrides: { writer: { brief: { prompt: '服务器文字' } } } } }; fireEvent.click(screen.getByRole('button', { name: '保存草稿' })); const reload = await screen.findByRole('button', { name: '放弃本地修改并加载服务器版本' }); expect(prompt).toHaveValue('本地文字'); fireEvent.click(reload); expect(prompt).toHaveValue('服务器文字'); expect(mock.saveTeamDraft).toHaveBeenCalledOnce(); });
  it('recognizes navigation module without using document CRUD', () => { expect(readStudioContext(new URL(studioLocation('p','agent-team'), 'http://local').search, 'p').studio).toBe('agent-team'); });
});
