import { useCallback, useEffect, useRef, useState } from 'react';
import { api } from '@/lib/api';
import { useCharacters } from '@/lib/queries/characters';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PrevisStage } from './stage';
import { durationOf, emptyScene, importDirectorScene, parseActions, parseSceneCommand, validateScene, type Actor, type Clip, type Scene, type Vec } from './model';
import { readStudioContext } from '../studio-context';
import { listStudioDocuments, saveStudioDocument } from '../studio-api';
import { ActionProposalEditor } from './proposal-editor';
import { AiPrevisPlanner } from './ai-previs-planner';
import { cameraStroke } from './camera-stroke';
import { Camera, Move3D, Spline, Box, Crosshair } from 'lucide-react';

type Doc = { id: string; name: string; data: Scene; revision: number; updated_at: string };
type Output = { id: string; kind: 'frame' | 'video'; filename: string; revision: number; created_at: string; source?: Scene['source'] };
const labels = { walk: '走', run: '跑', turn: '转身', sit: '坐下' };
const download = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 60000); };
function NumberField({ label, value, onChange, min }: { label: string; value: number; min?: number; onChange: (n: number) => void }) {
  return <label className="space-y-1 text-xs">{label}<Input aria-label={label} type="number" min={min} step="0.1" value={value} onChange={e => { if (e.target.value !== '' && Number.isFinite(Number(e.target.value))) onChange(Number(e.target.value)); }} /></label>;
}
export function PrevisStudio({ project }: { project: string }) {
  const context = readStudioContext(window.location.search, project);
  return <PrevisEditor key={`${project}:${context.node ?? context.group ?? context.episode ?? 'direct'}`} project={project} />;
}
function PrevisEditor({ project }: { project: string }) {
  const [scene, setScene] = useState<Scene>(() => { const initial = emptyScene(); const context = readStudioContext(window.location.search, project); if (context.node || context.group || context.episode) initial.source = { type: context.node ? 'canvas' : context.group ? 'narrative_group' : 'episode', id: context.node ?? context.group ?? String(context.episode) }; return initial; });
  const selectionKey = useRef(`previs-selection:${project}:${scene.source ? `${scene.source.type}:${scene.source.id}` : 'direct'}`).current;
  const restored = useRef(false);
  const [docs, setDocs] = useState<Doc[]>([]), [id, setId] = useState<string>(() => crypto.randomUUID()), [revision, setRevision] = useState(0);
  const [name, setName] = useState('未命名预演'), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false);
  const latestEdit = useRef({ scene, name, id, dirty }); latestEdit.current = { scene, name, id, dirty };
  const [error, setError] = useState(''), [actorId, setActorId] = useState(''), [clipId, setClipId] = useState('');
  const [time, setTime] = useState(0), [playing, setPlaying] = useState(false), [recording, setRecording] = useState(false);
  const [command, setCommand] = useState(''), [proposal, setProposal] = useState<Clip[]>([]), [actorName, setActorName] = useState('');
  const [mode, setMode] = useState<'actor' | 'target' | 'camera' | 'prop' | 'path'>('actor');
  const [pathDuration, setPathDuration] = useState(5);
  const [drawnPath, setDrawnPath] = useState<Scene['camera']>([]);
  useEffect(() => { setDrawnPath([]); }, [id]);
  const [video, setVideo] = useState('');
  const [outputs, setOutputs] = useState<Output[]>([]), [uploading, setUploading] = useState(false);
  const [sceneCommand, setSceneCommand] = useState(''), [sceneProposal, setSceneProposal] = useState<Scene | null>(null);
  const canvas = useRef<HTMLCanvasElement>(null), recorder = useRef<MediaRecorder | null>(null);
  const characters = useCharacters(project);
  const endpoint = `api/v1/projects/${encodeURIComponent(project)}/studios/previs`;
  const outputEndpoint = `api/v1/projects/${encodeURIComponent(project)}/studios/previs-tools/outputs`;
  const duration = durationOf(scene), actor = scene.actors.find(a => a.id === actorId), clip = scene.clips.find(c => c.id === clipId);
  const change = (next: Scene) => { if (recording) { setError('录制期间场景已锁定，完成导出后可继续编辑'); return; } const problem = validateScene(next); if (problem) { setError(problem); return; } setError(''); setScene(next); setDirty(true); };
  const load = useCallback(async () => { try { const documents = await listStudioDocuments<Scene>(project, 'previs'); setDocs(documents); if (!restored.current) { restored.current = true; let selected: string | null = null; try { selected = localStorage.getItem(selectionKey); } catch { /* storage unavailable */ } const doc = documents.find(d => d.id === selected); if (doc && !latestEdit.current.dirty) { const problem = validateScene(doc.data); if (problem) throw new Error(problem); setScene(doc.data); setName(doc.name); setId(doc.id); setRevision(doc.revision); } else if (selected && !doc) setError('上次选择的预演已被删除或不可访问，请选择其他草稿'); } } catch (e) { setError(`草稿读取失败：${String(e)}`); } }, [project, selectionKey]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const abort = new AbortController(); void api.get(outputEndpoint, { signal: abort.signal }).json<{ data: Output[] }>().then(r => setOutputs(r.data)).catch(e => { if (!abort.signal.aborted) setError(`预演素材读取失败：${String(e)}`); }); return () => abort.abort(); }, [outputEndpoint]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  useEffect(() => { window.dispatchEvent(new CustomEvent('studio-dirty', { detail: { dirty, module: 'previs' } })); }, [dirty]);
  useEffect(() => () => { window.dispatchEvent(new CustomEvent('studio-dirty', { detail: { dirty: false, module: 'previs' } })); }, []);
  useEffect(() => { if (!playing) return; let raf = 0; let last = performance.now(); const tick = (now: number) => { const dt = (now - last) / 1000; last = now; setTime(t => { if (t + dt >= duration) { setPlaying(false); if (recorder.current?.state === 'recording') setTimeout(() => recorder.current?.stop(), 80); return duration; } return t + dt; }); raf = requestAnimationFrame(tick); }; raf = requestAnimationFrame(tick); return () => cancelAnimationFrame(raf); }, [playing, duration]);
  useEffect(() => () => { const r = recorder.current; if (r) { r.onstop = null; r.onerror = null; if (r.state !== 'inactive') r.stop(); r.stream.getTracks().forEach(track => track.stop()); recorder.current = null; } }, []);
  useEffect(() => { if (revision > 0) { try { localStorage.setItem(selectionKey, id); } catch { /* storage unavailable */ } } }, [id, revision, selectionKey]);
  useEffect(() => () => { if (video) URL.revokeObjectURL(video); }, [video]);
  const save = async () => { if (busy) return; const problem = validateScene(scene); if (problem) { setError(problem); window.dispatchEvent(new Event('studio-save-failed-previs')); return; } setBusy(true); try { const result = await saveStudioDocument(project, 'previs', id, { name, data: scene, expected_revision: revision }); if (latestEdit.current.id === id) { setRevision(result.revision); if (latestEdit.current.scene === scene && latestEdit.current.name === name) setDirty(false); } await load(); } catch (e) { setError(`保存失败（版本冲突请重新加载草稿，当前编辑仍保留）：${String(e)}`); window.dispatchEvent(new Event('studio-save-failed-previs')); } finally { setBusy(false); } };
  const saveRef = useRef(save); saveRef.current = save;
  useEffect(() => { const handler = () => { void saveRef.current(); }; window.addEventListener('studio-save-previs', handler); return () => window.removeEventListener('studio-save-previs', handler); }, []);
  const persistOutput = async (blob: Blob, filename: string, frameTime?: number) => {
    setUploading(true);
    try { const form = new FormData(); form.set('file', blob, filename); form.set('manifest', JSON.stringify({ scene, revision, time: frameTime })); const { data } = await api.post(outputEndpoint, { body: form, retry: 0, timeout: 120000 }).json<{ data: Output }>(); setOutputs(list => [data, ...list.filter(item => item.id !== data.id)]); }
    catch (e) { setError(`文件已下载，但项目素材登记失败。可保留下载文件后重新导出登记：${String(e)}`); }
    finally { setUploading(false); }
  };
  const selectDoc = async (docId: string) => { if (recording || recorder.current) { setError('录制期间不能切换预演草稿'); return; } if (dirty && !window.confirm('当前预演尚未保存，放弃修改并加载所选版本？')) return; try { const { data } = await api.get(`${endpoint}/${docId}`).json<{ data: Doc }>(); if (recorder.current) return; const problem = validateScene(data.data); if (problem) throw new Error(problem); setScene(data.data); setName(data.name); setId(data.id); setRevision(data.revision); setDirty(false); setClipId(''); setActorId(''); setProposal([]); setSceneProposal(null); setPlaying(false); setTime(0); setError(''); } catch (e) { setError(`草稿加载失败：${String(e)}`); } };
  const addActor = (name: string, characterRef?: string) => { if (!name.trim()) { setError('请输入演员名称或选择项目角色'); return; } const a: Actor = { id: crypto.randomUUID(), name, humanoid: !characterRef, position: [0, 0, 0], yaw: 0, characterRef }; change({ ...scene, actors: [...scene.actors, a] }); setActorId(a.id); setActorName(''); };
  const updateActor = (patch: Partial<Actor>) => { if (actor) change({ ...scene, actors: scene.actors.map(a => a.id === actor.id ? { ...a, ...patch } : a) }); };
  const updateClip = (patch: Partial<Clip>) => { if (clip) change({ ...scene, clips: scene.clips.map(c => c.id === clip.id ? { ...c, ...patch } : c) }); };
  const addClip = (action: Clip['action']) => { if (!actor) return; const start = Math.max(0, ...scene.clips.filter(c => c.actorId === actor.id).map(c => c.start + c.duration)); const c: Clip = { id: crypto.randomUUID(), actorId: actor.id, action, start, duration: 2, target: actor.position, yaw: actor.yaw }; change({ ...scene, clips: [...scene.clips, c] }); setClipId(c.id); };
  const ground = (position: Vec, dragging = false) => { if (recording || (dragging && mode === 'prop')) return; if (mode === 'actor') updateActor({ position }); else if (mode === 'target') updateClip({ target: position }); else if (mode === 'prop') change({ ...scene, props: [...scene.props, { id: crypto.randomUUID(), position: [position[0], 0.3, position[2]], scale: [1, 0.6, 1] }] }); else { const key = { id: crypto.randomUUID(), time: Number(time.toFixed(2)), position: [position[0], 3, position[2]] as Vec, target: actor?.position ?? [0, 1, 0] as Vec }; change({ ...scene, camera: [...scene.camera.filter(k => Math.abs(k.time - time) > 0.05), key] }); } };
  const drawPath = (points: Vec[]) => { if (recording) return; try { setDrawnPath(cameraStroke(points, Number(time.toFixed(2)), pathDuration, 3, actor ? [actor.position[0], 1, actor.position[2]] : [0, 1, 0])); setError(''); } catch (e) { setError(String(e)); } };
  const exportFrame = () => { canvas.current?.toBlob(blob => { if (blob) { download(blob, `${name}-${time.toFixed(2)}s.png`); void persistOutput(blob, `${name}.png`, time); download(new Blob([JSON.stringify({ project, scene, revision, time }, null, 2)], { type: 'application/json' }), `${name}-frame-manifest.json`); } else setError('参考帧导出失败'); }, 'image/png'); };
  const exportVideo = () => {
    if (recorder.current || recording) return;
    if (!canvas.current || typeof MediaRecorder === 'undefined' || !canvas.current.captureStream) { setError('此浏览器不支持本地视频录制，请使用支持 MediaRecorder 的浏览器'); return; }
    const mimeType = ['video/webm;codecs=vp9', 'video/webm;codecs=vp8', 'video/webm'].find(t => MediaRecorder.isTypeSupported(t));
    if (!mimeType) { setError('浏览器不支持 WebM 导出'); return; }
    try {
      const stream = canvas.current.captureStream(30), chunks: BlobPart[] = [];
      const r = new MediaRecorder(stream, { mimeType }); recorder.current = r; setRecording(true);
      r.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
      r.onstop = () => {
        stream.getTracks().forEach(t => t.stop()); recorder.current = null; setPlaying(false); setRecording(false);
        const blob = new Blob(chunks, { type: mimeType });
        if (blob.size) { setVideo(URL.createObjectURL(blob)); download(blob, `${name}.webm`); void persistOutput(blob, `${name}.webm`); download(new Blob([JSON.stringify({ project, scene, revision, duration }, null, 2)], { type: 'application/json' }), `${name}-video-manifest.json`); }
        else setError('录制没有产生视频数据');
      };
      r.onerror = () => { r.onstop = null; if (r.state !== 'inactive') r.stop(); stream.getTracks().forEach(t => t.stop()); recorder.current = null; setPlaying(false); setError('视频录制失败，请保留草稿重试'); setRecording(false); };
      setTime(0); setPlaying(false);
      requestAnimationFrame(() => requestAnimationFrame(() => { if (recorder.current !== r) return; r.start(100); setPlaying(true); }));
    } catch (e) { recorder.current?.stream.getTracks().forEach(t => t.stop()); recorder.current = null; setRecording(false); setError(`视频录制失败：${String(e)}`); }
  };
  return <section className="previs-workspace" aria-label="3D 预演工作室">
    <div className="flex flex-wrap items-center gap-2"><Input disabled={recording} className="max-w-56" aria-label="预演名称" value={name} onChange={e => { setName(e.target.value); setDirty(true); }} /><Button onClick={() => void save()} disabled={busy || recording}>{busy ? '保存中' : `保存版本${dirty ? ' *' : ''}`}</Button><select disabled={recording} aria-label="加载预演草稿" className="rounded border bg-background p-2 text-sm" value="" onChange={e => void selectDoc(e.target.value)}><option value="">加载已保存草稿</option>{docs.map(d => <option key={d.id} value={d.id}>{d.name} · v{d.revision}</option>)}</select><span className="text-xs text-muted-foreground">当前版本 v{revision}</span></div>
    {error && <div role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</div>}
    <fieldset disabled={recording} className="previs-columns">
      <aside className="previs-config space-y-3">
        <h3 className="font-medium">演员与场景</h3><select aria-label="添加项目角色" value="" className="w-full rounded border bg-background p-2" onChange={e => { if (e.target.value) addActor(e.target.value, e.target.value); }}><option value="">从项目角色添加</option>{characters.data?.data.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}</select>
        {characters.isError && <p className="text-xs text-destructive">项目角色读取失败</p>}
        <Input aria-label="简化演员名称" placeholder="简化演员名称" value={actorName} onChange={e => setActorName(e.target.value)} /><Button variant="outline" onClick={() => addActor(actorName)}>创建简化人形演员</Button>
        <select aria-label="当前演员" className="w-full rounded border bg-background p-2" value={actorId} onChange={e => setActorId(e.target.value)}><option value="">选择演员</option>{scene.actors.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select>
        {actor && <><label className="flex gap-2 text-sm"><input type="checkbox" checked={actor.humanoid} onChange={e => updateActor({ humanoid: e.target.checked })} />确认适配人形动作</label><div className="grid grid-cols-2 gap-2">{[0, 2].map(i => <NumberField key={i} label={`演员 ${i === 0 ? 'X' : 'Z'}`} value={actor.position[i]} onChange={n => { const p = [...actor.position] as Vec; p[i] = n; updateActor({ position: p }); }} />)}<NumberField label="演员朝向" value={actor.yaw} onChange={yaw => updateActor({ yaw })} /></div><Button variant="outline" onClick={() => { change({ ...scene, actors: scene.actors.filter(a => a.id !== actor.id), clips: scene.clips.filter(c => c.actorId !== actor.id) }); setActorId(''); }}>删除演员及动作</Button></>}
        <label className="block text-xs">画面拖动/点击编辑<select aria-label="场景拖动模式" value={mode} className="mt-1 w-full rounded border bg-background p-2" onChange={e => { setMode(e.target.value as typeof mode); setPlaying(false); setDrawnPath([]); }}><option value="actor">演员站位</option><option value="target">所选动作终点 / 坐姿目标</option><option value="camera">播放头位置添加摄影机路径点</option><option value="path">画线运镜</option><option value="prop">添加白模物件 / 座椅</option></select></label>
        <div className="grid grid-cols-2 gap-2"><NumberField label="灯光方向" value={scene.light.yaw} onChange={yaw => change({ ...scene, light: { ...scene.light, yaw } })} /><NumberField label="灯光亮度" value={scene.light.intensity} min={0} onChange={intensity => change({ ...scene, light: { ...scene.light, intensity: Math.max(0, intensity) } })} /></div>
        <Button variant="outline" onClick={() => change({ ...scene, props: [] })}>清空白模物件</Button>
        <label className="block text-xs">导入 director_world 场景快照 JSON<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { const data = JSON.parse(await file.text()); const imported = importDirectorScene(data.scene ?? data); change({ ...imported, source: scene.source }); setActorId(''); setClipId(''); setTime(0); } catch (err) { setError(`场景导入失败：${String(err)}`); } }} /></label>
        {scene.source && <p className="text-xs text-muted-foreground">来源：{scene.source.type} / {scene.source.id}</p>}
        <details><summary className="cursor-pointer text-xs">文字搭景（本地规则）</summary><Input aria-label="文字搭景" placeholder="演员站位 2,3" value={sceneCommand} onChange={e => setSceneCommand(e.target.value)} /><p className="my-1 text-xs text-muted-foreground">演员站位 2,3 · 添加座椅 2,3 · 机位 8,6,10 · 灯光 35,1.4</p><Button variant="outline" onClick={() => { try { setSceneProposal(parseSceneCommand(sceneCommand, scene, actorId, Number(time.toFixed(2)))); } catch (e) { setError(String(e)); } }}>解析搭景</Button>{sceneProposal && <div className="space-y-2 text-xs"><p>待采纳：{sceneCommand}。应用后可在站位、灯光和摄影机面板继续编辑。</p><Button onClick={() => { change(sceneProposal); setSceneProposal(null); }}>应用场景调整</Button><Button variant="outline" onClick={() => setSceneProposal(null)}>放弃</Button></div>}</details>
        <label className="block text-xs">参考图片（仅构图参考）<input type="file" accept="image/*" onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { setError('参考图请小于 2 MB'); return; } const reader = new FileReader(); reader.onload = () => change({ ...scene, reference: String(reader.result) }); reader.readAsDataURL(file); }} /></label>{scene.reference && <img alt="场景参考" src={scene.reference} className="max-h-40 rounded object-contain" />}
      </aside>
      <div className="previs-main min-w-0 space-y-3">
        <div className="flex flex-wrap items-center gap-1 rounded-xl border bg-card p-2" role="toolbar" aria-label="三维画面工具">
          {([{id:'actor',label:'移动演员',icon:Move3D},{id:'target',label:'动作终点',icon:Crosshair},{id:'camera',label:'放置机位',icon:Camera},{id:'path',label:'画线运镜',icon:Spline},{id:'prop',label:'添加物件',icon:Box}] as const).map(tool=><Button key={tool.id} variant={mode===tool.id?'secondary':'ghost'} size="sm" aria-pressed={mode===tool.id} onClick={()=>{setMode(tool.id);setPlaying(false);setDrawnPath([]);}}><tool.icon className="size-4"/>{tool.label}</Button>)}
        </div>
        <p className="text-xs text-muted-foreground">{mode==='path'?'按住三维地面画出路线，松开后确认应用；摄影机高度为 3 米，可在路径数字编辑中调整。':mode==='actor'?`${actor ? `已选中 ${actor.name}，` : '先选择演员，'}在画面中拖动调整站位。`:mode==='target'?'先选择动作片段，再在画面中拖动设置终点。':mode==='prop'?'点击地面添加白模物件或座椅。':'点击地面，在当前播放头位置放置摄影机。'}</p>
        {mode==='path' && <div className="flex flex-wrap items-end gap-2 rounded-lg border p-3"><NumberField label="画线路径时长（秒）" min={0.1} value={pathDuration} onChange={setPathDuration}/>{drawnPath.length>0 && <><span className="text-xs">{drawnPath.length} 个路径点 · {drawnPath[0].time.toFixed(1)}–{drawnPath[drawnPath.length-1].time.toFixed(1)} 秒；应用将替换这个时段的机位。</span><Button onClick={()=>{const start=drawnPath[0].time,end=drawnPath[drawnPath.length-1].time;change({...scene,camera:[...scene.camera.filter(k=>k.time<start||k.time>end),...drawnPath].sort((a,b)=>a.time-b.time)});setDrawnPath([]);}}>应用画线路径</Button><Button variant="ghost" onClick={()=>setDrawnPath([])}>取消路径</Button></>}</div>}
        <div className="previs-viewport"><PrevisStage scene={scene} time={time} canvasRef={canvas} onError={setError} onGround={recording || playing || mode==='path' ? ()=>{} : ground} onStroke={mode==='path' && !recording && !playing ? drawPath : undefined} /></div>
        <div className="previs-transport"><Button disabled={recording} onClick={() => { if (time >= duration) setTime(0); setPlaying(!playing); }}>{playing ? '暂停' : '播放'}</Button><Button variant="outline" disabled={recording} onClick={exportFrame}>导出摄影机参考帧</Button><Button variant="outline" disabled={recording} onClick={exportVideo}>{recording ? `录制 ${time.toFixed(1)} / ${duration.toFixed(1)} 秒` : '导出白模动作视频'}</Button><span className="self-center text-xs">{time.toFixed(2)} / {duration.toFixed(2)} 秒</span></div>
        <label className="block text-xs">时间尺 / 播放头<input aria-label="播放头" className="w-full" type="range" min={0} max={duration} step="0.01" value={time} disabled={recording} onChange={e => { setPlaying(false); setTime(Number(e.target.value)); }} /></label>
        <div className="previs-timeline overflow-x-auto rounded border p-3"><div style={{ minWidth: Math.max(520, duration * 45) }}><div className="relative ml-24 h-6 text-xs">{Array.from({ length: Math.floor(duration) + 1 }, (_, i) => <span key={i} className="absolute" style={{ left: `${i / duration * 100}%` }}>{i}s</span>)}</div>{scene.actors.map(a => <div key={a.id} className="flex h-12 items-center border-t"><button className="w-24 shrink-0 truncate text-left text-xs" onClick={() => setActorId(a.id)}>{a.name}</button><div className="relative h-9 flex-1 bg-muted/30">{scene.clips.filter(c => c.actorId === a.id).map(c => <div key={c.id} role="button" tabIndex={0} aria-label={`${a.name} ${labels[c.action]} ${c.start}秒`} onKeyDown={e => { if (e.key === 'Enter') { setClipId(c.id); setActorId(a.id); } }} className={`absolute flex h-8 cursor-grab select-none items-center rounded border px-2 text-xs ${clipId === c.id ? 'bg-primary text-primary-foreground' : 'bg-secondary'}`} style={{ left: `${c.start / duration * 100}%`, width: `${c.duration / duration * 100}%` }} onPointerDown={e => { setClipId(c.id); setActorId(a.id); const x = e.clientX, width = e.currentTarget.parentElement!.clientWidth; const resize = (e.target as HTMLElement).dataset.resize; e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.onpointerup = end => { const delta = (end.clientX - x) / width * duration; change({ ...scene, clips: scene.clips.map(item => item.id === c.id ? { ...item, ...(resize ? { duration: Math.round((c.duration + delta) * 10) / 10 } : { start: Math.round((c.start + delta) * 10) / 10 }) } : item) }); }; }}>{labels[c.action]}<span data-resize="true" aria-label="拖动调整动作长度" className="absolute inset-y-0 right-0 w-3 cursor-ew-resize border-l" /></div>)}<div className="pointer-events-none absolute inset-y-0 w-px bg-destructive" style={{ left: `${time / duration * 100}%` }} /></div></div>)}<div className="flex h-10 items-center border-t"><span className="w-24 text-xs">摄影机轨道</span><div className="relative h-8 flex-1">{scene.camera.map(k => <button key={k.id} title={`摄影机 ${k.time}s`} className="absolute top-1 text-primary" style={{ left: `${k.time / duration * 100}%` }} onClick={() => setTime(k.time)}>◆</button>)}</div></div></div></div>
        <div className="flex flex-wrap gap-2">{Object.entries(labels).map(([key, label]) => <Button key={key} variant="outline" disabled={!actor?.humanoid || recording} onClick={() => addClip(key as Clip['action'])}>+ {label}</Button>)}</div>
      </div>
      <aside className="min-w-0 space-y-3 xl:col-span-2 2xl:col-span-1 2xl:max-h-[78vh] 2xl:overflow-y-auto">
        {clip && <div className="grid gap-2 rounded border p-3 sm:grid-cols-3"><NumberField label="动作开始秒" min={0} value={clip.start} onChange={start => updateClip({ start })} /><NumberField label="动作时长秒" min={0.1} value={clip.duration} onChange={duration => updateClip({ duration })} /><NumberField label="目标朝向" value={clip.yaw} onChange={yaw => updateClip({ yaw })} />{[0, 2].map(i => <NumberField key={i} label={`动作终点 ${i ? 'Z' : 'X'}`} value={clip.target[i]} onChange={n => { const target = [...clip.target] as Vec; target[i] = n; updateClip({ target }); }} />)}<Button variant="outline" onClick={() => { change({ ...scene, clips: scene.clips.filter(c => c.id !== clip.id) }); setClipId(''); }}>删除动作</Button></div>}
        <details className="rounded border p-3"><summary className="cursor-pointer text-sm">摄影机路径数字编辑</summary>{scene.camera.map(k => <div key={k.id} className="my-2 grid grid-cols-4 gap-2"><NumberField label="摄影机时间" min={0} value={k.time} onChange={time => change({ ...scene, camera: scene.camera.map(c => c.id === k.id ? { ...c, time } : c) })} />{[0, 1, 2].map(i => <NumberField key={i} label={`机位 ${['X', 'Y', 'Z'][i]}`} value={k.position[i]} onChange={n => { const position = [...k.position] as Vec; position[i] = n; change({ ...scene, camera: scene.camera.map(c => c.id === k.id ? { ...c, position } : c) }); }} />)}<Button variant="outline" disabled={scene.camera.length <= 1} onClick={() => change({ ...scene, camera: scene.camera.filter(c => c.id !== k.id) })}>删除路径点</Button></div>)}</details>
        <div className="space-y-2 rounded border p-3"><p className="text-sm">快速动作指令 · 免费本地规则（固定语法，不调用 AI）</p><textarea className="min-h-20 w-full rounded border bg-background p-2 text-sm" aria-label="快速动作指令" value={command} onChange={e => setCommand(e.target.value)} placeholder="走 3 秒 到 4,2；转身 2 秒 朝 90 度" /><Button variant="outline" disabled={!actor || recording} onClick={() => { try { setProposal(parseActions(command, actor!, Math.max(time, ...scene.clips.filter(c => c.actorId === actorId).map(c => c.start + c.duration)))); setError(''); } catch (e) { setError(String(e)); } }}>解析为可编辑动作</Button>{proposal.length > 0 && <div className="space-y-2"><ActionProposalEditor actors={scene.actors} clips={proposal} onChange={setProposal} /><Button disabled={recording} onClick={() => { const next = { ...scene, clips: [...scene.clips, ...proposal] }; if (!validateScene(next)) { change(next); setClipId(proposal[0].id); setProposal([]); } else setError(validateScene(next)!); }}>采纳已编辑动作</Button><Button variant="outline" onClick={() => setProposal([])}>放弃</Button></div>}</div>
        {video && <video aria-label="导出的白模动作预演" src={video} controls className="w-full rounded" />}
        <div className="space-y-2 rounded border p-3"><h3 className="text-sm font-medium">项目预演素材 {uploading && '· 登记中'}</h3>{outputs.length === 0 && <p className="text-xs text-muted-foreground">导出的参考帧和视频将在这里保留，可随时重新打开。</p>}<div className="grid gap-3 sm:grid-cols-2">{outputs.map(output => <div key={output.id} className="space-y-1 rounded border p-2">{output.kind === 'frame' ? <img alt="已保存的预演参考帧" src={`/${outputEndpoint}/${output.id}/media`} className="w-full rounded" /> : <video controls preload="metadata" src={`/${outputEndpoint}/${output.id}/media`} className="w-full rounded" />}<p className="text-xs text-muted-foreground">v{output.revision} · {new Date(output.created_at).toLocaleString()}{output.source ? ` · 来源 ${output.source.id}` : ''}</p><a className="text-xs underline" href={`/${outputEndpoint}/${output.id}/media`} target="_blank" rel="noreferrer">打开 / 下载素材</a></div>)}</div></div>
        <p className="text-xs text-muted-foreground">输出包含场景、动作与角色引用清单。当前生成模型尚未连接动作控制；下载参考帧或视频不会自动用于生成，也不保证逐帧复现。</p>
<AiPrevisPlanner key={id} project={project} scene={scene} disabled={recording} onAdopt={change} /><div className="rounded-xl border p-4 text-xs text-muted-foreground"><h3 className="mb-2 font-medium text-foreground">从搭景到表演</h3><ol className="list-decimal space-y-2 pl-4"><li>添加角色，确认人形动作适配。</li><li>移动站位、画出运镜，或向 AI 描述调整。</li><li>在时间轴添加走、跑、转身和坐下，拖动片段调整开始时间。</li><li>预览后导出，回到画布添加参考素材。</li></ol></div></aside>
    </fieldset>
  </section>;
}
