import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import type { Actor, Clip, Scene, Vec } from './model';

export function ActionProposalEditor({ actors, clips, onChange }: { actors: Actor[]; clips: Clip[]; onChange: (clips: Clip[]) => void }) {
  const update = (id: string, patch: Partial<Clip>) => onChange(clips.map(c => c.id === id ? { ...c, ...patch } : c));
  return <div className="space-y-2">{clips.map((c, index) => <fieldset key={c.id} className="grid gap-2 rounded border p-2 sm:grid-cols-3"><legend className="text-xs">建议动作 {index + 1}</legend><label className="text-xs">演员<select className="w-full rounded border bg-background p-2" value={c.actorId} onChange={e => update(c.id, { actorId: e.target.value })}>{actors.map(a => <option key={a.id} value={a.id} disabled={!a.humanoid}>{a.name}</option>)}</select></label><label className="text-xs">动作<select className="w-full rounded border bg-background p-2" value={c.action} onChange={e => update(c.id, { action: e.target.value as Clip['action'] })}>{Object.entries({ walk: '走', run: '跑', turn: '转身', sit: '坐下' }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{(['start', 'duration', 'yaw'] as const).map(key => <label key={key} className="text-xs">{{ start: '开始秒', duration: '时长秒', yaw: '朝向' }[key]}<Input aria-label={`建议${index + 1}-${key}`} type="number" step="0.1" value={c[key]} onChange={e => update(c.id, { [key]: Number(e.target.value) })} /></label>)}{([0, 2] as const).map(i => <label key={i} className="text-xs">目标 {i ? 'Z' : 'X'}<Input aria-label={`建议${index + 1}-target-${i}`} type="number" value={c.target[i]} onChange={e => { const target = [...c.target] as Vec; target[i] = Number(e.target.value); update(c.id, { target }); }} /></label>)}<Button variant="outline" onClick={() => onChange(clips.filter(item => item.id !== c.id))}>移除建议动作</Button></fieldset>)}</div>;
}

export function SceneProposalEditor({ value, onChange }: { value: Scene; onChange: (scene: Scene) => void }) {
  return <div className="space-y-3"><ActionProposalEditor actors={value.actors} clips={value.clips} onChange={clips => onChange({ ...value, clips })} /><details><summary className="cursor-pointer text-sm">编辑场景、机位、灯光与物件参数</summary><div className="space-y-3 p-2">{value.actors.map(a => <div key={a.id}><p className="text-sm">{a.name} 站位</p><VectorEditor label={a.name} value={a.position} onChange={position => onChange({ ...value, actors: value.actors.map(actor => actor.id === a.id ? { ...actor, position } : actor) })} /></div>)}{value.camera.map((key, index) => <div key={key.id} className="space-y-2 rounded border p-2"><p className="text-sm">机位点 {index + 1}</p><label className="text-xs">时间秒<Input type="number" value={key.time} onChange={e => onChange({ ...value, camera: value.camera.map(c => c.id === key.id ? { ...c, time: Number(e.target.value) } : c) })} /></label><VectorEditor label="摄影机位置" value={key.position} onChange={position => onChange({ ...value, camera: value.camera.map(c => c.id === key.id ? { ...c, position } : c) })} /><VectorEditor label="摄影机目标" value={key.target} onChange={target => onChange({ ...value, camera: value.camera.map(c => c.id === key.id ? { ...c, target } : c) })} /></div>)}{value.props.map((prop, index) => <div key={prop.id}><p className="text-sm">物件 {index + 1}</p><VectorEditor label="物件位置" value={prop.position} onChange={position => onChange({ ...value, props: value.props.map(p => p.id === prop.id ? { ...p, position } : p) })} /><VectorEditor label="物件尺寸" value={prop.scale} onChange={scale => onChange({ ...value, props: value.props.map(p => p.id === prop.id ? { ...p, scale } : p) })} /><Button variant="outline" onClick={() => onChange({ ...value, props: value.props.filter(p => p.id !== prop.id) })}>移除物件</Button></div>)}<label className="text-xs">灯光方向<Input type="number" value={value.light.yaw} onChange={e => onChange({ ...value, light: { ...value.light, yaw: Number(e.target.value) } })} /></label><label className="text-xs">灯光亮度<Input type="number" value={value.light.intensity} onChange={e => onChange({ ...value, light: { ...value.light, intensity: Number(e.target.value) } })} /></label></div></details></div>;
}

function VectorEditor({ label, value, onChange }: { label: string; value: Vec; onChange: (v: Vec) => void }) {
  return <div className="grid grid-cols-3 gap-2">{value.map((v, i) => <label className="text-xs" key={i}>{label} {['X', 'Y', 'Z'][i]}<Input type="number" step="0.1" value={v} onChange={e => { const next = [...value] as Vec; next[i] = Number(e.target.value); onChange(next); }} /></label>)}</div>;
}
